# mode: outline (arquivo grande — apenas assinaturas)

# [OUTLINE — corpo omitido por limite de tamanho]
"""TestForge — Normalizador de Gravação."""
import json
import logging
import os
import re as _re
from collections import Counter
from datetime import datetime
from typing import Optional
from urllib.parse import urlparse, urlunparse
from .model import LocatorCandidate, SemanticAction, SemanticTarget, SemanticTestCase
from testforge.handlers import HANDLERS
from testforge.metrics.metrics_repository import MetricsRepository
_MATERIAL_ICONS = ...
def _clean_text(text: str, max_len: int=60):
    """Remove material icon ligatures from text content and truncate."""
    ...
_GENERIC_TEXT_SET = ...
def _is_generic_text(text: str):
    """Check if text is a generic UI label that produces brittle locators."""
    ...
def _attr_css_variants(attr_name: str, value: str, tag: str, exact_score: float, reason: str):
    """Generate CSS attribute variant selectors for locator healing."""
    ...
def _compound_candidates(target_data: dict, tag: str):
    """Generate compound attribute selectors combining 2 attributes."""
    ...
class RecordingNormalizer:
    def __init__(self, use_v2_locator: bool=False, use_pipeline: bool=False):
        ...
    def _build_load_dedup_compact_pipeline(self):
        """Fase 5: constroi pipeline Pipes&Filters lazy."""
        ...
    def _build_audit_pipeline(self):
        ...
    def normalize(self, recording_dir: str, test_id: str='', application: str='', base_url: str=''):
        ...
    def _severity_rank(severity: str):
        ...
    def _load_bug_reports(self, recording_dir: str):
        ...
    def _attach_bug_refs(self, stc: SemanticTestCase, bug_reports: list[dict]):
        ...
    def _input_visible_at_click(recording_dir: str, click_step, target_id: str):
        """Sprint A2 (2026-06-30): le field_snapshots.jsonl e retorna True se o"""
        ...
    def _is_tab_like_click(cls, click_step):
        ...
    def _eliminate_prefill_clicks(self, steps: list, recording_dir: str=''):
        """Marca como pulados clicks seguidos imediatamente por fill no mesmo elemento."""
        ...
    def _audit_blind_spots(self, stc):
        """Detecta padroes onde intencao do usuario provavelmente foi perdida pelo gravador."""
        ...
    def _reconstruct_intents(self, stc, recording_dir: str):
        """Reconstroi intencoes de fill a partir de fontes de evidencia (IntentReconstructor inline)."""
        ...
    def _build_field_value_map(self, stc):
        """Constroi field_value_map ligando identificadores de campo, valores e intencoes."""
        ...
    def _merge_user_supplied_values(self, stc):
        """CS-4a: le field_value_map.json escrito pelo prompt `--complete`."""
        ...
    def _canonical_field_key(key: str):
        """Normaliza identificador de campo para chave canonica de correspondencia."""
        ...
    def _build_fill_intention(step, field_key: str, value: str, step_index: int):
        """Constroi string de intencao legivel para acao de fill em campo."""
        ...
    def _compact_keypress_sequences(self, raw_events: list):
        """Converte sequencias de eventos keypress de caractere unico em evento fill acumulado."""
        ...
    def _compact_fill_events(self, raw_events: list):
        """Compacta eventos fill sequenciais no mesmo elemento."""
        ...
    def _remove_snapshot_duplicates(self, raw_events: list):
        """Remove eventos fill de snapshot periodico DOM (ciclos duplicados)."""
        ...
    def _convert_event(self, raw: dict):
        ...
    def _convert_step(self, step: dict):
        ...
    def _finalize_target_with_candidates(self, target: SemanticTarget, candidates: list[LocatorCandidate], context: dict):
        """Ensures target exits with candidates, synthesizing a CSS fallback when possible."""
        ...
    def _build_target(self, target_data: dict):
        ...
    def _steps_identical(self, a: SemanticAction, b: SemanticAction):
        """Verifica se dois passos sao identicos (mesma action, value, target candidates)."""
        ...
    def _detect_stale_asserts(self, steps: list):
        """Anota asserts potencialmente obsoletos por refill posterior."""
        ...
    def _merge_asserts_by_timestamp(self, steps: list, asserts: list):
        """Intercala asserts no lugar cronologico correto entre os steps."""
        ...
    def _deduplicate_steps(self, steps: list):
        """Marca passos duplicados consecutivos com skip_reason."""
        ...
    def _mark_non_actionable(self, steps: list):
        """Marca passos sem alto acionavel como pulados."""
        ...
    def _detect_step_dependencies(self, steps: list):
        """Detecta dependencias entre passos para prevencao de falha em cascata."""
        ...
    def _detect_overlay_steps(self, steps: list):
        """Detecta passos dentro de containers overlay (calendario, modal, dialog)."""
        ...
    def _detect_navigation_clicks(self, steps: list):
        """Detecta clicks que causam mudancas de URL (navegacao SPA)."""
        ...
    def _normalize_url(url: str):
        """Remove barra final e params de consulta para comparacao de URL."""
        ...
    def _detect_missing_fills(self, steps: list):
        """Detecta clicks em inputs sem eventos fill (campos com mascara de moeda)."""
        ...
    def _ir_all(self, recording_dir: str, steps: list):
        """Executa todas estrategias IR, retorna entradas FieldValueMap deduplicadas."""
        ...
    def _ir_keystroke_buffer(self, recording_dir: str, steps: list):
        """Sprint L (2026-06-30): le keystroke_buffer.jsonl e reconstroi o"""
        ...
    def _ir_reconstruct_from_keystrokes(session: list[dict]):
        """Aplica eventos keydown sequenciais para reconstruir string final."""
        ...
    def _ir_inline_field_values(self, recording_dir: str, steps: list):
        """H21: le eventos inline_field_value de raw_events.jsonl"""
        ...
    def _ir_polling(self, recording_dir: str, steps: list):
        """Extrai valores de field_snapshots.jsonl com fonte=polling."""
        ...
    def _ir_value_mutations(self, recording_dir: str, steps: list):
        """Le value_mutations.jsonl — mudancas programaticas de valor."""
        ...
    def _ir_snapshots(self, recording_dir: str, steps: list):
        """Detecta mudancas de valor/checked entre snapshots de campo."""
        ...
    def _ir_make_snapshot_entry(self, fp, value, ids, tag, name, label, placeholder, element_id, steps, ts, source, suffix):
        ...
    def _ir_final_state(self, recording_dir: str, steps: list):
        """Le final_state_snapshot.json como fallback."""
        ...
    def _ir_form_values(self, steps: list):
        """Extrai form_values de contextos de passos submit."""
        ...
    def _ir_network(self, recording_dir: str, steps: list):
        """Analisa payloads de requisicoes POST/PUT para valores de campos."""
        ...
    def _ir_detect_masked_field(value: str, raw_value: str=''):
        """Detecta se valor corresponde a padrao de campo com mascara."""
        ...
    def _verify_recording_fingerprint(self, recording_dir: str):
        """Le recording_metadata.json, compara bloco fingerprint com"""
        ...
    def _fresh_dedupe_stats():
        """Retorna dict de estatisticas de dedup zerado."""
        ...
    def _ir_dedupe_entries(self, entries: list[dict]):
        """Deduplica por field_key, mantendo fonte de maior prioridade."""
        ...
    def _ir_find_nearest_step_index(steps: list, timestamp: str):
        """Encontra indice do passo mais proximo dado timestamp."""
        ...
    def _ir_parse_payload(post_data: str, url: str):
        """Analisa payload POST para extrair pares chave/valor."""
        ...
    def _ir_build_field_identifiers(steps: list):
        """Constroi mapa de identificadores de campo dos passos."""
        ...
    def _ir_match_by_url(payload_url: str, steps: list):
        """Corresponde URL de payload a passo por URL."""
        ...
    def _ir_correlate_payload_key(key: str, value: str, payload: dict, steps: list, field_identifiers: dict):
        """Correlaciona chave de payload de rede com passo correspondente."""
        ...

