from __future__ import annotations
from typing import Any, Callable, Protocol, runtime_checkable

from testforge.core.models.artifact import ArtifactPaths
from testforge.core.models.data import DataContract
from testforge.core.models.fingerprint import Fingerprint
from testforge.core.models.step import RecordedStep, StepResult
from testforge.core.models.test import TestArtifact


@runtime_checkable
class ArtifactSchemaContract(Protocol):
    def build_artifact(self, test_name: str, output_dir: str) -> TestArtifact: ...
    def ensure_directory(self, artifact: TestArtifact) -> None: ...
    def resolve_paths(self, artifact: TestArtifact) -> ArtifactPaths: ...
    def validate(self, artifact: TestArtifact) -> bool: ...


@runtime_checkable
class ErrorContract(Protocol):
    def handle(self, error: Exception, context: dict[str, Any]) -> StepResult: ...
    def classify(self, error: Exception) -> str: ...
    def retry(self, fn: Callable, max_attempts: int, context: dict[str, Any]) -> Any: ...


@runtime_checkable
class FingerprintContract(Protocol):
    def capture_recording(self, step: RecordedStep) -> None: ...
    def freeze_storage(self) -> None: ...
    def prepare_curation(self, failure_context: str, error_message: str) -> None: ...
    def get_fingerprint(self) -> Fingerprint: ...


@runtime_checkable
class DataContractProtocol(Protocol):
    def load(self, path: str) -> DataContract: ...
    def save(self, contract: DataContract, path: str) -> None: ...
    def validate(self, contract: DataContract, script_fields: set[str]) -> list[str]: ...
    def merge(self, base: DataContract, override: DataContract) -> DataContract: ...
