"""TestForge — Pipeline stages, manifest, and inspector.

Documents and introspects the four-stage data transformation pipeline:

Stage 1: raw_events (capture)
    Source: Browser event listeners injected by RecorderController.
    Format: raw_events.jsonl — one JSON object per line.
    Content: RawRecordedEvent (click, fill, navigation, submit, postback).
    Purpose: Lossless capture of every browser interaction.

Stage 2: steps (curated)
    Source: User-initiated actions (clicks, asserts via Shift+A).
    Format: steps.jsonl — one JSON object per curated step.
    Content: User-intended actions with explicit target selectors.
    Purpose: Human-curated test steps with assertion decisions.

Stage 3: semantic_steps (compiled)
    Source: RecordingNormalizer transforms raw_events + steps into SemanticTestCase.
    Format: semantic_steps.jsonl — metadata header + one step per line.
    Content: SemanticAction with locator candidates, skip_reason, context.
    Purpose: Machine-readable audit trail of every compiled step.

Stage 4: script (executable)
    Source: PlaywrightCompiler generates from SemanticTestCase.
    Format: test_<id>.py — Python file using playwright.sync_api.
    Content: Runnable Playwright test with fallback selector loops.
    Purpose: Executable test that replays the recorded user flow.

Data Flow:
    Browser → raw_events.jsonl + steps.jsonl → RecordingNormalizer
    → SemanticTestCase → PlaywrightCompiler → test_*.py + semantic_steps.jsonl
"""

import json
import os
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class PipelineStage(Enum):
    """The four stages of the TestForge data transformation pipeline.

    Each stage represents a distinct artifact in the recording→execution flow.
    """

    RAW_EVENTS = "raw_events"
    STEPS = "steps"
    SEMANTIC_STEPS = "semantic_steps"
    SCRIPT = "script"

    @property
    def label(self) -> str:
        """Human-readable stage name."""
        labels = {
            PipelineStage.RAW_EVENTS: "Raw Events",
            PipelineStage.STEPS: "Curated Steps",
            PipelineStage.SEMANTIC_STEPS: "Semantic Steps",
            PipelineStage.SCRIPT: "Executable Script",
        }
        return labels[self]

    @property
    def stage_type(self) -> str:
        """Stage classification: capture, curated, compiled, or executable."""
        types = {
            PipelineStage.RAW_EVENTS: "capture",
            PipelineStage.STEPS: "curated",
            PipelineStage.SEMANTIC_STEPS: "compiled",
            PipelineStage.SCRIPT: "executable",
        }
        return types[self]

    @property
    def file_name(self) -> str:
        """Default file name for this stage's artifact."""
        names = {
            PipelineStage.RAW_EVENTS: "raw_events.jsonl",
            PipelineStage.STEPS: "steps.jsonl",
            PipelineStage.SEMANTIC_STEPS: "semantic_steps.jsonl",
            PipelineStage.SCRIPT: None,  # Script name varies by test_id
        }
        return names[self]

    @property
    def description(self) -> str:
        """Detailed description of this pipeline stage."""
        descriptions = {
            PipelineStage.RAW_EVENTS: (
                "Browser events captured by injected JS listeners. "
                "Every click, fill, navigation, submit, and postback is recorded "
                "with full target info (tag, text, role, accessible_name, bounding_box, "
                "class_list, aria_attrs, data_attrs). Stored as JSONL for append-only writes."
            ),
            PipelineStage.STEPS: (
                "User-curated test steps captured via keyboard shortcuts (Shift+A for asserts) "
                "or explicit step recording. Includes assertion type (textual, estado, visivel, "
                "automatico), expected values, and explicit element selectors. "
                "Optional fields: blocking, depends_on for dependency chains."
            ),
            PipelineStage.SEMANTIC_STEPS: (
                "Compiled intermediate representation produced by RecordingNormalizer. "
                "Each step is a SemanticAction with ranked LocatorCandidates, "
                "skip_reason flags for non-actionable/duplicate steps, "
                "and dependency chain metadata (blocking, depends_on). "
                "Serves as the audit trail and debugging artifact."
            ),
            PipelineStage.SCRIPT: (
                "Final executable Playwright Python script generated by PlaywrightCompiler. "
                "Contains fallback selector loops for self-healing, "
                "data-driven test support via external JSON fixtures, "
                "and expect_navigation wrappers for form submissions. "
                "Ready to run with pytest + pytest-playwright."
            ),
        }
        return descriptions[self]

    @property
    def consumes(self) -> list["PipelineStage"]:
        """Which upstream stages this stage depends on."""
        upstream = {
            PipelineStage.RAW_EVENTS: [],
            PipelineStage.STEPS: [],
            PipelineStage.SEMANTIC_STEPS: [PipelineStage.RAW_EVENTS, PipelineStage.STEPS],
            PipelineStage.SCRIPT: [PipelineStage.SEMANTIC_STEPS],
        }
        return upstream[self]

    @property
    def produces(self) -> list["PipelineStage"]:
        """Which downstream stages consume this stage's output."""
        downstream = {
            PipelineStage.RAW_EVENTS: [PipelineStage.SEMANTIC_STEPS],
            PipelineStage.STEPS: [PipelineStage.SEMANTIC_STEPS],
            PipelineStage.SEMANTIC_STEPS: [PipelineStage.SCRIPT],
            PipelineStage.SCRIPT: [],
        }
        return downstream[self]


@dataclass
class PipelineManifest:
    """Tracks the existence and paths of all four pipeline stage files.

    Used to discover what stages have been executed for a given recording directory.
    """

    recording_dir: str
    raw_events_path: str = ""
    steps_path: str = ""
    semantic_steps_path: str = ""
    script_path: str = ""

    def __post_init__(self):
        self.refresh()

    def refresh(self) -> None:
        """Scan recording directory and update paths for found stage files."""
        if not os.path.isdir(self.recording_dir):
            return

        raw_events = os.path.join(self.recording_dir, "raw_events.jsonl")
        if os.path.isfile(raw_events):
            self.raw_events_path = raw_events

        steps = os.path.join(self.recording_dir, "steps.jsonl")
        if os.path.isfile(steps):
            self.steps_path = steps

        semantic_steps = os.path.join(self.recording_dir, "semantic_steps.jsonl")
        if os.path.isfile(semantic_steps):
            self.semantic_steps_path = semantic_steps

        # Script files follow pattern test_*.py
        for entry in os.listdir(self.recording_dir):
            if entry.startswith("test_") and entry.endswith(".py"):
                self.script_path = os.path.join(self.recording_dir, entry)
                break

    @property
    def stages_present(self) -> list[PipelineStage]:
        """Return list of stages whose artifacts are present."""
        present: list[PipelineStage] = []
        if self.raw_events_path:
            present.append(PipelineStage.RAW_EVENTS)
        if self.steps_path:
            present.append(PipelineStage.STEPS)
        if self.semantic_steps_path:
            present.append(PipelineStage.SEMANTIC_STEPS)
        if self.script_path:
            present.append(PipelineStage.SCRIPT)
        return present

    @property
    def stages_missing(self) -> list[PipelineStage]:
        """Return list of stages whose artifacts are absent."""
        present_set = set(self.stages_present)
        return [s for s in PipelineStage if s not in present_set]

    @property
    def is_complete(self) -> bool:
        """True if all four stages are present."""
        return len(self.stages_present) == 4

    @property
    def pipeline_depth(self) -> int:
        """How many stages deep the pipeline has progressed (0-4)."""
        return len(self.stages_present)

    def stage_path(self, stage: PipelineStage) -> Optional[str]:
        """Get the file path for a specific stage, or None if absent."""
        mapping = {
            PipelineStage.RAW_EVENTS: self.raw_events_path,
            PipelineStage.STEPS: self.steps_path,
            PipelineStage.SEMANTIC_STEPS: self.semantic_steps_path,
            PipelineStage.SCRIPT: self.script_path,
        }
        path = mapping.get(stage, "")
        return path if path else None

    def to_dict(self) -> dict:
        """Serialize manifest to dictionary."""
        return {
            "recording_dir": self.recording_dir,
            "stages_present": [s.value for s in self.stages_present],
            "stages_missing": [s.value for s in self.stages_missing],
            "is_complete": self.is_complete,
            "pipeline_depth": self.pipeline_depth,
            "paths": {
                "raw_events": self.raw_events_path or None,
                "steps": self.steps_path or None,
                "semantic_steps": self.semantic_steps_path or None,
                "script": self.script_path or None,
            },
        }


class PipelineInspector:
    """Introspects pipeline stage files and extracts statistics.

    Reads each stage's artifact file and produces a summary of contents.
    Useful for debugging, auditing, and CI verification.
    """

    @staticmethod
    def inspect_raw_events(file_path: str) -> dict:
        """Inspect a raw_events.jsonl file.

        Returns dict with event_count, event_types histogram, and metadata.
        """
        if not os.path.isfile(file_path):
            raise FileNotFoundError(f"File not found: {file_path}")

        events = []
        with open(file_path) as f:
            for line in f:
                line = line.strip()
                if line:
                    events.append(json.loads(line))

        type_counts: dict[str, int] = {}
        urls: set[str] = set()
        has_screenshots = False
        has_dom_snapshots = False

        for evt in events:
            etype = evt.get("type", "unknown")
            type_counts[etype] = type_counts.get(etype, 0) + 1
            if evt.get("url"):
                urls.add(evt["url"])
            if evt.get("screenshot"):
                has_screenshots = True
            if evt.get("dom_snapshot"):
                has_dom_snapshots = True

        return {
            "stage": PipelineStage.RAW_EVENTS.value,
            "file": file_path,
            "event_count": len(events),
            "event_types": type_counts,
            "unique_urls": sorted(urls),
            "has_screenshots": has_screenshots,
            "has_dom_snapshots": has_dom_snapshots,
        }

    @staticmethod
    def inspect_steps(file_path: str) -> dict:
        """Inspect a steps.jsonl file.

        Returns dict with step_count, action histogram, assert_types present.
        """
        if not os.path.isfile(file_path):
            raise FileNotFoundError(f"File not found: {file_path}")

        steps = []
        with open(file_path) as f:
            for line in f:
                line = line.strip()
                if line:
                    steps.append(json.loads(line))

        action_counts: dict[str, int] = {}
        assert_types: list[str] = []
        has_blocking = False
        has_dependencies = False

        for step in steps:
            action = step.get("action", "unknown")
            action_counts[action] = action_counts.get(action, 0) + 1
            if action == "assert" and step.get("assert_type"):
                atype = step["assert_type"]
                if atype not in assert_types:
                    assert_types.append(atype)
            if step.get("blocking"):
                has_blocking = True
            if step.get("depends_on"):
                has_dependencies = True

        return {
            "stage": PipelineStage.STEPS.value,
            "file": file_path,
            "step_count": len(steps),
            "actions": action_counts,
            "assert_types": assert_types,
            "has_blocking_steps": has_blocking,
            "has_dependency_chains": has_dependencies,
        }

    @staticmethod
    def inspect_semantic_steps(file_path: str) -> dict:
        """Inspect a semantic_steps.jsonl file.

        Returns dict with step_count, skip_reason breakdown, action histogram.
        """
        if not os.path.isfile(file_path):
            raise FileNotFoundError(f"File not found: {file_path}")

        lines = []
        with open(file_path) as f:
            for line in f:
                line = line.strip()
                if line:
                    lines.append(json.loads(line))

        metadata = {}
        steps = []
        for obj in lines:
            if obj.get("type") == "metadata":
                metadata = obj
            else:
                steps.append(obj)

        action_counts: dict[str, int] = {}
        skip_reasons: dict[str, int] = {}
        total_candidates = 0

        for step in steps:
            action = step.get("action", "unknown")
            action_counts[action] = action_counts.get(action, 0) + 1
            if step.get("skip_reason"):
                reason = step["skip_reason"]
                skip_reasons[reason] = skip_reasons.get(reason, 0) + 1
            if step.get("target") and step["target"].get("candidates"):
                total_candidates += len(step["target"]["candidates"])

        return {
            "stage": PipelineStage.SEMANTIC_STEPS.value,
            "file": file_path,
            "metadata": metadata,
            "step_count": len(steps),
            "actions": action_counts,
            "skip_reasons": skip_reasons,
            "total_locator_candidates": total_candidates,
        }

    @staticmethod
    def inspect_script(file_path: str) -> dict:
        """Inspect a generated test_*.py script.

        Returns dict with line count, function_name, test steps found.
        """
        if not os.path.isfile(file_path):
            raise FileNotFoundError(f"File not found: {file_path}")

        with open(file_path) as f:
            content = f.read()

        lines = content.split("\n")
        step_count = 0
        function_name = ""
        has_data_driven = "DATA_FILE" in content or "_data" in content
        has_fallback = "for _sel in _sels:" in content

        for line in lines:
            if line.startswith("def test_"):
                function_name = line.split("(")[0].replace("def ", "").strip()
            if line.strip().startswith("# Step "):
                step_count += 1

        return {
            "stage": PipelineStage.SCRIPT.value,
            "file": file_path,
            "line_count": len(lines),
            "function_name": function_name,
            "test_steps": step_count,
            "has_data_driven_support": has_data_driven,
            "has_fallback_loops": has_fallback,
        }

    @classmethod
    def inspect_stage(cls, stage: PipelineStage, file_path: str) -> dict:
        """Auto-dispatch to correct inspector based on stage type.

        Args:
            stage: PipelineStage enum member.
            file_path: Path to the stage artifact file.

        Returns:
            Dict with stage inspection results.
        """
        inspectors = {
            PipelineStage.RAW_EVENTS: cls.inspect_raw_events,
            PipelineStage.STEPS: cls.inspect_steps,
            PipelineStage.SEMANTIC_STEPS: cls.inspect_semantic_steps,
            PipelineStage.SCRIPT: cls.inspect_script,
        }
        inspect_fn = inspectors.get(stage)
        if not inspect_fn:
            raise ValueError(f"No inspector for stage: {stage}")
        return inspect_fn(file_path)

    @classmethod
    def inspect_directory(cls, recording_dir: str) -> dict[str, dict]:
        """Inspect a recording directory and report on all found stages.

        Args:
            recording_dir: Path to a recording session directory.

        Returns:
            Dict mapping stage value to inspection results (absent stages omitted).
        """
        manifest = PipelineManifest(recording_dir)
        results: dict[str, dict] = {}

        for stage in PipelineStage:
            path = manifest.stage_path(stage)
            if path:
                try:
                    results[stage.value] = cls.inspect_stage(stage, path)
                except Exception as exc:
                    results[stage.value] = {"error": str(exc)}

        return results
